image: maven:alpine

stages:
  - test
  - deploy

build-job:
  stage: test
  script:
    - mvn clean compile

test-job:
  stage: test
  script:
    - mvn clean verify

deploy-job:
  stage: deploy
  script:
    - cp ci/settings.xml ~/.m2/settings.xml
    - mvn clean deploy
