image: maven:alpine

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - mvn clean compile

test-job:
  stage: test
  script:
    - mvn clean verify
    
deploy-job:
  stage: deploy
  script:
    - mvn clean install