/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Bankenländerliste
 */
public enum BankList {
  Oesterreich("AT"),
  Belgien("BE"),
  Bulgarien("BG"),
  Schweiz("CH"),
  Zypern("CY"),
  TschechischeRepublik("CZ"),
  Deutschland("DE"),
  Daenemark("DK"),
  Estland("EE"),
  Spanien("ES"),
  Finnland("FI"),
  Frankreich("FR"),
  Grossbritannien("GB"),
  Griechenland("GR"),
  Kroatien("HR"),
  Ungarn("HU"),
  Irland("IE"),
  Island("IS"),
  Italien("IT"),
  Liechtenstein("LI"),
  Litauen("LT"),
  Luxemburg("LU"),
  Lettland("LV"),
  Malta("MT"),
  Martinique("MQ"),
  Niederlande("NL"),
  Norwegen("NO"),
  Polen("PL"),
  Portugal("PT"),
  Rumaenien("RO"),
  Schweden("SE"),
  Slowenien("SI"),
  Slowakei("SK");

  private String value;

  BankList(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BankList fromValue(String text) {
    for (BankList b : BankList.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

