/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.joda.time.DateTime;

/**
 * Body
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-26T00:23:10.016+02:00")
public class Body {
  @JsonProperty("type")
  private BuyOrSell type = null;

  @JsonProperty("max_amount")
  private Float maxAmount = null;

  @JsonProperty("price")
  private Float price = null;

  @JsonProperty("min_amount")
  private Float minAmount = null;

  @JsonProperty("end_datetime")
  private DateTime endDatetime = null;

  @JsonProperty("new_order_for_remaining_amount")
  private Integer newOrderForRemainingAmount = null;

  @JsonProperty("min_trust_level")
  private TrustLevel minTrustLevel = null;

  @JsonProperty("only_kyc_full")
  private Integer onlyKycFull = null;

  @JsonProperty("payment_option")
  private PaymentOption paymentOption = null;

  @JsonProperty("seat_of_bank")
  private BankList seatOfBank = null;

  public Body type(BuyOrSell type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public BuyOrSell getType() {
    return type;
  }

  public void setType(BuyOrSell type) {
    this.type = type;
  }

  public Body maxAmount(Float maxAmount) {
    this.maxAmount = maxAmount;
    return this;
  }

   /**
   * Maximale Menge der zu handelnden Bitcoins
   * @return maxAmount
  **/
  @ApiModelProperty(example = "null", value = "Maximale Menge der zu handelnden Bitcoins")
  public Float getMaxAmount() {
    return maxAmount;
  }

  public void setMaxAmount(Float maxAmount) {
    this.maxAmount = maxAmount;
  }

  public Body price(Float price) {
    this.price = price;
    return this;
  }

   /**
   * Preis pro Bitcoin in Euro
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "Preis pro Bitcoin in Euro")
  public Float getPrice() {
    return price;
  }

  public void setPrice(Float price) {
    this.price = price;
  }

  public Body minAmount(Float minAmount) {
    this.minAmount = minAmount;
    return this;
  }

   /**
   * Mindest-Menge der zu handelnden Bitcoins
   * @return minAmount
  **/
  @ApiModelProperty(example = "null", value = "Mindest-Menge der zu handelnden Bitcoins")
  public Float getMinAmount() {
    return minAmount;
  }

  public void setMinAmount(Float minAmount) {
    this.minAmount = minAmount;
  }

  public Body endDatetime(DateTime endDatetime) {
    this.endDatetime = endDatetime;
    return this;
  }

   /**
   * Enddatum (mindestens 5 Tage in der Zukunft) des Angebots. Format gemäß RFC 3339 (Bsp: 2015-01-20T15:00:00+02:00). Zulässige Werte für die Minuten sind: 00, 15 , 30, 45
   * @return endDatetime
  **/
  @ApiModelProperty(example = "null", value = "Enddatum (mindestens 5 Tage in der Zukunft) des Angebots. Format gemäß RFC 3339 (Bsp: 2015-01-20T15:00:00+02:00). Zulässige Werte für die Minuten sind: 00, 15 , 30, 45")
  public DateTime getEndDatetime() {
    return endDatetime;
  }

  public void setEndDatetime(DateTime endDatetime) {
    this.endDatetime = endDatetime;
  }

  public Body newOrderForRemainingAmount(Integer newOrderForRemainingAmount) {
    this.newOrderForRemainingAmount = newOrderForRemainingAmount;
    return this;
  }

   /**
   * Neues Angebot mit Restmenge anlegen, wenn nur eine Teilmenge aus dem Angebot bedient wurde.
   * @return newOrderForRemainingAmount
  **/
  @ApiModelProperty(example = "null", value = "Neues Angebot mit Restmenge anlegen, wenn nur eine Teilmenge aus dem Angebot bedient wurde.")
  public Integer getNewOrderForRemainingAmount() {
    return newOrderForRemainingAmount;
  }

  public void setNewOrderForRemainingAmount(Integer newOrderForRemainingAmount) {
    this.newOrderForRemainingAmount = newOrderForRemainingAmount;
  }

  public Body minTrustLevel(TrustLevel minTrustLevel) {
    this.minTrustLevel = minTrustLevel;
    return this;
  }

   /**
   * Get minTrustLevel
   * @return minTrustLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public TrustLevel getMinTrustLevel() {
    return minTrustLevel;
  }

  public void setMinTrustLevel(TrustLevel minTrustLevel) {
    this.minTrustLevel = minTrustLevel;
  }

  public Body onlyKycFull(Integer onlyKycFull) {
    this.onlyKycFull = onlyKycFull;
    return this;
  }

   /**
   * Handelspartner muss vollständig identifiziert sein.
   * @return onlyKycFull
  **/
  @ApiModelProperty(example = "null", value = "Handelspartner muss vollständig identifiziert sein.")
  public Integer getOnlyKycFull() {
    return onlyKycFull;
  }

  public void setOnlyKycFull(Integer onlyKycFull) {
    this.onlyKycFull = onlyKycFull;
  }

  public Body paymentOption(PaymentOption paymentOption) {
    this.paymentOption = paymentOption;
    return this;
  }

   /**
   * Get paymentOption
   * @return paymentOption
  **/
  @ApiModelProperty(example = "null", value = "")
  public PaymentOption getPaymentOption() {
    return paymentOption;
  }

  public void setPaymentOption(PaymentOption paymentOption) {
    this.paymentOption = paymentOption;
  }

  public Body seatOfBank(BankList seatOfBank) {
    this.seatOfBank = seatOfBank;
    return this;
  }

   /**
   * Erlaubte Länder, in denen die Bank des Handelspartners ihren Sitz haben darf (ISO 3166-2
   * @return seatOfBank
  **/
  @ApiModelProperty(example = "null", value = "Erlaubte Länder, in denen die Bank des Handelspartners ihren Sitz haben darf (ISO 3166-2")
  public BankList getSeatOfBank() {
    return seatOfBank;
  }

  public void setSeatOfBank(BankList seatOfBank) {
    this.seatOfBank = seatOfBank;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body body = (Body) o;
    return Objects.equals(this.type, body.type) &&
        Objects.equals(this.maxAmount, body.maxAmount) &&
        Objects.equals(this.price, body.price) &&
        Objects.equals(this.minAmount, body.minAmount) &&
        Objects.equals(this.endDatetime, body.endDatetime) &&
        Objects.equals(this.newOrderForRemainingAmount, body.newOrderForRemainingAmount) &&
        Objects.equals(this.minTrustLevel, body.minTrustLevel) &&
        Objects.equals(this.onlyKycFull, body.onlyKycFull) &&
        Objects.equals(this.paymentOption, body.paymentOption) &&
        Objects.equals(this.seatOfBank, body.seatOfBank);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, maxAmount, price, minAmount, endDatetime, newOrderForRemainingAmount, minTrustLevel, onlyKycFull, paymentOption, seatOfBank);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    maxAmount: ").append(toIndentedString(maxAmount)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    minAmount: ").append(toIndentedString(minAmount)).append("\n");
    sb.append("    endDatetime: ").append(toIndentedString(endDatetime)).append("\n");
    sb.append("    newOrderForRemainingAmount: ").append(toIndentedString(newOrderForRemainingAmount)).append("\n");
    sb.append("    minTrustLevel: ").append(toIndentedString(minTrustLevel)).append("\n");
    sb.append("    onlyKycFull: ").append(toIndentedString(onlyKycFull)).append("\n");
    sb.append("    paymentOption: ").append(toIndentedString(paymentOption)).append("\n");
    sb.append("    seatOfBank: ").append(toIndentedString(seatOfBank)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

