/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.joda.time.DateTime;

/**
 * Error
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T15:01:02.402+02:00")
public class Error {
  @JsonProperty("message")
  private String message = null;

  @JsonProperty("start")
  private DateTime start = null;

  @JsonProperty("end")
  private DateTime end = null;

  public Error message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Infotext
   * @return message
  **/
  @ApiModelProperty(example = "null", value = "Infotext")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public Error start(DateTime start) {
    this.start = start;
    return this;
  }

   /**
   * Start der Arbeiten (Format: 2015-04-07T12:23:04+02:00 gemäß RFC 3339)
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "Start der Arbeiten (Format: 2015-04-07T12:23:04+02:00 gemäß RFC 3339)")
  public DateTime getStart() {
    return start;
  }

  public void setStart(DateTime start) {
    this.start = start;
  }

  public Error end(DateTime end) {
    this.end = end;
    return this;
  }

   /**
   * Voraussichtliches Ende der Arbeiten (Format: 2015-04-07T12:23:04+02:00 gemäß RFC 3339)
   * @return end
  **/
  @ApiModelProperty(example = "null", value = "Voraussichtliches Ende der Arbeiten (Format: 2015-04-07T12:23:04+02:00 gemäß RFC 3339)")
  public DateTime getEnd() {
    return end;
  }

  public void setEnd(DateTime end) {
    this.end = end;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Error error = (Error) o;
    return Objects.equals(this.message, error.message) &&
        Objects.equals(this.start, error.start) &&
        Objects.equals(this.end, error.end);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, start, end);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Error {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

