/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.rainu.bitcoinde.model.InlineResponse2006DataBtcBalance;
import de.rainu.bitcoinde.model.InlineResponse2006DataEncryptedInformation;
import de.rainu.bitcoinde.model.InlineResponse2006DataFidorReservation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2006Data
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T13:21:29.350+02:00")
public class InlineResponse2006Data {
  @JsonProperty("btc_balance")
  private InlineResponse2006DataBtcBalance btcBalance = null;

  @JsonProperty("fidor_reservation")
  private InlineResponse2006DataFidorReservation fidorReservation = null;

  @JsonProperty("encrypted_information")
  private InlineResponse2006DataEncryptedInformation encryptedInformation = null;

  public InlineResponse2006Data btcBalance(InlineResponse2006DataBtcBalance btcBalance) {
    this.btcBalance = btcBalance;
    return this;
  }

   /**
   * Get btcBalance
   * @return btcBalance
  **/
  @ApiModelProperty(example = "null", value = "")
  public InlineResponse2006DataBtcBalance getBtcBalance() {
    return btcBalance;
  }

  public void setBtcBalance(InlineResponse2006DataBtcBalance btcBalance) {
    this.btcBalance = btcBalance;
  }

  public InlineResponse2006Data fidorReservation(InlineResponse2006DataFidorReservation fidorReservation) {
    this.fidorReservation = fidorReservation;
    return this;
  }

   /**
   * Get fidorReservation
   * @return fidorReservation
  **/
  @ApiModelProperty(example = "null", value = "")
  public InlineResponse2006DataFidorReservation getFidorReservation() {
    return fidorReservation;
  }

  public void setFidorReservation(InlineResponse2006DataFidorReservation fidorReservation) {
    this.fidorReservation = fidorReservation;
  }

  public InlineResponse2006Data encryptedInformation(InlineResponse2006DataEncryptedInformation encryptedInformation) {
    this.encryptedInformation = encryptedInformation;
    return this;
  }

   /**
   * Get encryptedInformation
   * @return encryptedInformation
  **/
  @ApiModelProperty(example = "null", value = "")
  public InlineResponse2006DataEncryptedInformation getEncryptedInformation() {
    return encryptedInformation;
  }

  public void setEncryptedInformation(InlineResponse2006DataEncryptedInformation encryptedInformation) {
    this.encryptedInformation = encryptedInformation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2006Data inlineResponse2006Data = (InlineResponse2006Data) o;
    return Objects.equals(this.btcBalance, inlineResponse2006Data.btcBalance) &&
        Objects.equals(this.fidorReservation, inlineResponse2006Data.fidorReservation) &&
        Objects.equals(this.encryptedInformation, inlineResponse2006Data.encryptedInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(btcBalance, fidorReservation, encryptedInformation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2006Data {\n");
    
    sb.append("    btcBalance: ").append(toIndentedString(btcBalance)).append("\n");
    sb.append("    fidorReservation: ").append(toIndentedString(fidorReservation)).append("\n");
    sb.append("    encryptedInformation: ").append(toIndentedString(encryptedInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

