/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Infos zur BTC-Balance
 */
@ApiModel(description = "Infos zur BTC-Balance")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T13:21:29.350+02:00")
public class InlineResponse2006DataBtcBalance {
  @JsonProperty("total_amount")
  private String totalAmount = null;

  @JsonProperty("available_amount")
  private String availableAmount = null;

  @JsonProperty("reserved_amount")
  private String reservedAmount = null;

  public InlineResponse2006DataBtcBalance totalAmount(String totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

   /**
   * Aktuelles BTC-Guthaben
   * @return totalAmount
  **/
  @ApiModelProperty(example = "null", value = "Aktuelles BTC-Guthaben")
  public String getTotalAmount() {
    return totalAmount;
  }

  public void setTotalAmount(String totalAmount) {
    this.totalAmount = totalAmount;
  }

  public InlineResponse2006DataBtcBalance availableAmount(String availableAmount) {
    this.availableAmount = availableAmount;
    return this;
  }

   /**
   * Aktuell verfügbares BTC-Guthaben
   * @return availableAmount
  **/
  @ApiModelProperty(example = "null", value = "Aktuell verfügbares BTC-Guthaben")
  public String getAvailableAmount() {
    return availableAmount;
  }

  public void setAvailableAmount(String availableAmount) {
    this.availableAmount = availableAmount;
  }

  public InlineResponse2006DataBtcBalance reservedAmount(String reservedAmount) {
    this.reservedAmount = reservedAmount;
    return this;
  }

   /**
   * Aktuell reserviertes BTC-Guthaben
   * @return reservedAmount
  **/
  @ApiModelProperty(example = "null", value = "Aktuell reserviertes BTC-Guthaben")
  public String getReservedAmount() {
    return reservedAmount;
  }

  public void setReservedAmount(String reservedAmount) {
    this.reservedAmount = reservedAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2006DataBtcBalance inlineResponse2006DataBtcBalance = (InlineResponse2006DataBtcBalance) o;
    return Objects.equals(this.totalAmount, inlineResponse2006DataBtcBalance.totalAmount) &&
        Objects.equals(this.availableAmount, inlineResponse2006DataBtcBalance.availableAmount) &&
        Objects.equals(this.reservedAmount, inlineResponse2006DataBtcBalance.reservedAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalAmount, availableAmount, reservedAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2006DataBtcBalance {\n");
    
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    availableAmount: ").append(toIndentedString(availableAmount)).append("\n");
    sb.append("    reservedAmount: ").append(toIndentedString(reservedAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

