/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2007Trades
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T12:15:09.755+02:00")
public class InlineResponse2007Trades {
  @JsonProperty("date")
  private Integer date = null;

  @JsonProperty("price")
  private Float price = null;

  @JsonProperty("amount")
  private Float amount = null;

  @JsonProperty("tid")
  private Integer tid = null;

  public InlineResponse2007Trades date(Integer date) {
    this.date = date;
    return this;
  }

   /**
   * Datum (Unixtimestamp)
   * @return date
  **/
  @ApiModelProperty(example = "null", value = "Datum (Unixtimestamp)")
  public Integer getDate() {
    return date;
  }

  public void setDate(Integer date) {
    this.date = date;
  }

  public InlineResponse2007Trades price(Float price) {
    this.price = price;
    return this;
  }

   /**
   * Preis pro Bitcoin (Euro)
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "Preis pro Bitcoin (Euro)")
  public Float getPrice() {
    return price;
  }

  public void setPrice(Float price) {
    this.price = price;
  }

  public InlineResponse2007Trades amount(Float amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Anzahl BTC
   * @return amount
  **/
  @ApiModelProperty(example = "null", value = "Anzahl BTC")
  public Float getAmount() {
    return amount;
  }

  public void setAmount(Float amount) {
    this.amount = amount;
  }

  public InlineResponse2007Trades tid(Integer tid) {
    this.tid = tid;
    return this;
  }

   /**
   * Eindeutige ID
   * @return tid
  **/
  @ApiModelProperty(example = "null", value = "Eindeutige ID")
  public Integer getTid() {
    return tid;
  }

  public void setTid(Integer tid) {
    this.tid = tid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007Trades inlineResponse2007Trades = (InlineResponse2007Trades) o;
    return Objects.equals(this.date, inlineResponse2007Trades.date) &&
        Objects.equals(this.price, inlineResponse2007Trades.price) &&
        Objects.equals(this.amount, inlineResponse2007Trades.amount) &&
        Objects.equals(this.tid, inlineResponse2007Trades.tid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, price, amount, tid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007Trades {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    tid: ").append(toIndentedString(tid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

