/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.rainu.bitcoinde.model.InlineResponse2007OrdersBids;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Array mit Bids / Asks
 */
@ApiModel(description = "Array mit Bids / Asks")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T13:21:29.350+02:00")
public class InlineResponse2007Orders {
  @JsonProperty("bids")
  private List<InlineResponse2007OrdersBids> bids = new ArrayList<InlineResponse2007OrdersBids>();

  @JsonProperty("asks")
  private List<InlineResponse2007OrdersBids> asks = new ArrayList<InlineResponse2007OrdersBids>();

  public InlineResponse2007Orders bids(List<InlineResponse2007OrdersBids> bids) {
    this.bids = bids;
    return this;
  }

  public InlineResponse2007Orders addBidsItem(InlineResponse2007OrdersBids bidsItem) {
    this.bids.add(bidsItem);
    return this;
  }

   /**
   * Get bids
   * @return bids
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InlineResponse2007OrdersBids> getBids() {
    return bids;
  }

  public void setBids(List<InlineResponse2007OrdersBids> bids) {
    this.bids = bids;
  }

  public InlineResponse2007Orders asks(List<InlineResponse2007OrdersBids> asks) {
    this.asks = asks;
    return this;
  }

  public InlineResponse2007Orders addAsksItem(InlineResponse2007OrdersBids asksItem) {
    this.asks.add(asksItem);
    return this;
  }

   /**
   * Get asks
   * @return asks
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InlineResponse2007OrdersBids> getAsks() {
    return asks;
  }

  public void setAsks(List<InlineResponse2007OrdersBids> asks) {
    this.asks = asks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007Orders inlineResponse2007Orders = (InlineResponse2007Orders) o;
    return Objects.equals(this.bids, inlineResponse2007Orders.bids) &&
        Objects.equals(this.asks, inlineResponse2007Orders.asks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bids, asks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007Orders {\n");
    
    sb.append("    bids: ").append(toIndentedString(bids)).append("\n");
    sb.append("    asks: ").append(toIndentedString(asks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

