/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.rainu.bitcoinde.model.Error;
import de.rainu.bitcoinde.model.InlineResponse20010AccountLedger;
import de.rainu.bitcoinde.model.Page;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20010
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T13:21:29.350+02:00")
public class InlineResponse20010 {
  @JsonProperty("account_ledger")
  private List<InlineResponse20010AccountLedger> accountLedger = new ArrayList<InlineResponse20010AccountLedger>();

  @JsonProperty("page")
  private Page page = null;

  @JsonProperty("errors")
  private List<Error> errors = new ArrayList<Error>();

  @JsonProperty("credits")
  private Integer credits = null;

  public InlineResponse20010 accountLedger(List<InlineResponse20010AccountLedger> accountLedger) {
    this.accountLedger = accountLedger;
    return this;
  }

  public InlineResponse20010 addAccountLedgerItem(InlineResponse20010AccountLedger accountLedgerItem) {
    this.accountLedger.add(accountLedgerItem);
    return this;
  }

   /**
   * Details zur Position
   * @return accountLedger
  **/
  @ApiModelProperty(example = "null", value = "Details zur Position")
  public List<InlineResponse20010AccountLedger> getAccountLedger() {
    return accountLedger;
  }

  public void setAccountLedger(List<InlineResponse20010AccountLedger> accountLedger) {
    this.accountLedger = accountLedger;
  }

  public InlineResponse20010 page(Page page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @ApiModelProperty(example = "null", value = "")
  public Page getPage() {
    return page;
  }

  public void setPage(Page page) {
    this.page = page;
  }

  public InlineResponse20010 errors(List<Error> errors) {
    this.errors = errors;
    return this;
  }

  public InlineResponse20010 addErrorsItem(Error errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Error> getErrors() {
    return errors;
  }

  public void setErrors(List<Error> errors) {
    this.errors = errors;
  }

  public InlineResponse20010 credits(Integer credits) {
    this.credits = credits;
    return this;
  }

   /**
   * Restliches Credit-Kontingent
   * @return credits
  **/
  @ApiModelProperty(example = "null", value = "Restliches Credit-Kontingent")
  public Integer getCredits() {
    return credits;
  }

  public void setCredits(Integer credits) {
    this.credits = credits;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20010 inlineResponse20010 = (InlineResponse20010) o;
    return Objects.equals(this.accountLedger, inlineResponse20010.accountLedger) &&
        Objects.equals(this.page, inlineResponse20010.page) &&
        Objects.equals(this.errors, inlineResponse20010.errors) &&
        Objects.equals(this.credits, inlineResponse20010.credits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountLedger, page, errors, credits);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20010 {\n");
    
    sb.append("    accountLedger: ").append(toIndentedString(accountLedger)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    credits: ").append(toIndentedString(credits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

