/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.rainu.bitcoinde.model.BuyOrSell;
import de.rainu.bitcoinde.model.OrderRequirement;
import de.rainu.bitcoinde.model.TradingPartner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse200Orders
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T13:21:29.350+02:00")
public class InlineResponse200Orders {
  @JsonProperty("order_id")
  private String orderId = null;

  @JsonProperty("type")
  private BuyOrSell type = null;

  @JsonProperty("max_amount")
  private Float maxAmount = null;

  @JsonProperty("min_amount")
  private Float minAmount = null;

  @JsonProperty("price")
  private Float price = null;

  @JsonProperty("max_volume")
  private Float maxVolume = null;

  @JsonProperty("min_volume")
  private Float minVolume = null;

  @JsonProperty("order_requirements_fullfilled")
  private Boolean orderRequirementsFullfilled = null;

  @JsonProperty("trading_partner_information")
  private TradingPartner tradingPartnerInformation = null;

  @JsonProperty("order_requirements")
  private OrderRequirement orderRequirements = null;

  public InlineResponse200Orders orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * ID des Angebots
   * @return orderId
  **/
  @ApiModelProperty(example = "null", value = "ID des Angebots")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public InlineResponse200Orders type(BuyOrSell type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public BuyOrSell getType() {
    return type;
  }

  public void setType(BuyOrSell type) {
    this.type = type;
  }

  public InlineResponse200Orders maxAmount(Float maxAmount) {
    this.maxAmount = maxAmount;
    return this;
  }

   /**
   * Maximal handelbare BTC-Menge
   * @return maxAmount
  **/
  @ApiModelProperty(example = "null", value = "Maximal handelbare BTC-Menge")
  public Float getMaxAmount() {
    return maxAmount;
  }

  public void setMaxAmount(Float maxAmount) {
    this.maxAmount = maxAmount;
  }

  public InlineResponse200Orders minAmount(Float minAmount) {
    this.minAmount = minAmount;
    return this;
  }

   /**
   * Mindestens handelbare BTC-Menge
   * @return minAmount
  **/
  @ApiModelProperty(example = "null", value = "Mindestens handelbare BTC-Menge")
  public Float getMinAmount() {
    return minAmount;
  }

  public void setMinAmount(Float minAmount) {
    this.minAmount = minAmount;
  }

  public InlineResponse200Orders price(Float price) {
    this.price = price;
    return this;
  }

   /**
   * Preis pro BTC in Euro
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "Preis pro BTC in Euro")
  public Float getPrice() {
    return price;
  }

  public void setPrice(Float price) {
    this.price = price;
  }

  public InlineResponse200Orders maxVolume(Float maxVolume) {
    this.maxVolume = maxVolume;
    return this;
  }

   /**
   * Max. Euro-Volumen der Order
   * @return maxVolume
  **/
  @ApiModelProperty(example = "null", value = "Max. Euro-Volumen der Order")
  public Float getMaxVolume() {
    return maxVolume;
  }

  public void setMaxVolume(Float maxVolume) {
    this.maxVolume = maxVolume;
  }

  public InlineResponse200Orders minVolume(Float minVolume) {
    this.minVolume = minVolume;
    return this;
  }

   /**
   * Min. Euro-Volumen der Order
   * @return minVolume
  **/
  @ApiModelProperty(example = "null", value = "Min. Euro-Volumen der Order")
  public Float getMinVolume() {
    return minVolume;
  }

  public void setMinVolume(Float minVolume) {
    this.minVolume = minVolume;
  }

  public InlineResponse200Orders orderRequirementsFullfilled(Boolean orderRequirementsFullfilled) {
    this.orderRequirementsFullfilled = orderRequirementsFullfilled;
    return this;
  }

   /**
   * Zeigt an, ob das Angebot bedient werden könnte oder nicht (Trust-Level, KYC-Full, Sitz der Bank etc.).
   * @return orderRequirementsFullfilled
  **/
  @ApiModelProperty(example = "null", value = "Zeigt an, ob das Angebot bedient werden könnte oder nicht (Trust-Level, KYC-Full, Sitz der Bank etc.).")
  public Boolean getOrderRequirementsFullfilled() {
    return orderRequirementsFullfilled;
  }

  public void setOrderRequirementsFullfilled(Boolean orderRequirementsFullfilled) {
    this.orderRequirementsFullfilled = orderRequirementsFullfilled;
  }

  public InlineResponse200Orders tradingPartnerInformation(TradingPartner tradingPartnerInformation) {
    this.tradingPartnerInformation = tradingPartnerInformation;
    return this;
  }

   /**
   * Infos zum User des Angebots
   * @return tradingPartnerInformation
  **/
  @ApiModelProperty(example = "null", value = "Infos zum User des Angebots")
  public TradingPartner getTradingPartnerInformation() {
    return tradingPartnerInformation;
  }

  public void setTradingPartnerInformation(TradingPartner tradingPartnerInformation) {
    this.tradingPartnerInformation = tradingPartnerInformation;
  }

  public InlineResponse200Orders orderRequirements(OrderRequirement orderRequirements) {
    this.orderRequirements = orderRequirements;
    return this;
  }

   /**
   * Get orderRequirements
   * @return orderRequirements
  **/
  @ApiModelProperty(example = "null", value = "")
  public OrderRequirement getOrderRequirements() {
    return orderRequirements;
  }

  public void setOrderRequirements(OrderRequirement orderRequirements) {
    this.orderRequirements = orderRequirements;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200Orders inlineResponse200Orders = (InlineResponse200Orders) o;
    return Objects.equals(this.orderId, inlineResponse200Orders.orderId) &&
        Objects.equals(this.type, inlineResponse200Orders.type) &&
        Objects.equals(this.maxAmount, inlineResponse200Orders.maxAmount) &&
        Objects.equals(this.minAmount, inlineResponse200Orders.minAmount) &&
        Objects.equals(this.price, inlineResponse200Orders.price) &&
        Objects.equals(this.maxVolume, inlineResponse200Orders.maxVolume) &&
        Objects.equals(this.minVolume, inlineResponse200Orders.minVolume) &&
        Objects.equals(this.orderRequirementsFullfilled, inlineResponse200Orders.orderRequirementsFullfilled) &&
        Objects.equals(this.tradingPartnerInformation, inlineResponse200Orders.tradingPartnerInformation) &&
        Objects.equals(this.orderRequirements, inlineResponse200Orders.orderRequirements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, type, maxAmount, minAmount, price, maxVolume, minVolume, orderRequirementsFullfilled, tradingPartnerInformation, orderRequirements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200Orders {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    maxAmount: ").append(toIndentedString(maxAmount)).append("\n");
    sb.append("    minAmount: ").append(toIndentedString(minAmount)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    maxVolume: ").append(toIndentedString(maxVolume)).append("\n");
    sb.append("    minVolume: ").append(toIndentedString(minVolume)).append("\n");
    sb.append("    orderRequirementsFullfilled: ").append(toIndentedString(orderRequirementsFullfilled)).append("\n");
    sb.append("    tradingPartnerInformation: ").append(toIndentedString(tradingPartnerInformation)).append("\n");
    sb.append("    orderRequirements: ").append(toIndentedString(orderRequirements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

