/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.rainu.bitcoinde.model.InlineResponse2005DataBtcBalance;
import de.rainu.bitcoinde.model.InlineResponse2005DataEncryptedInformation;
import de.rainu.bitcoinde.model.InlineResponse2005DataFidorReservation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2005Data
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T12:15:09.755+02:00")
public class InlineResponse2005Data {
  @JsonProperty("btc_balance")
  private InlineResponse2005DataBtcBalance btcBalance = null;

  @JsonProperty("fidor_reservation")
  private InlineResponse2005DataFidorReservation fidorReservation = null;

  @JsonProperty("encrypted_information")
  private InlineResponse2005DataEncryptedInformation encryptedInformation = null;

  public InlineResponse2005Data btcBalance(InlineResponse2005DataBtcBalance btcBalance) {
    this.btcBalance = btcBalance;
    return this;
  }

   /**
   * Get btcBalance
   * @return btcBalance
  **/
  @ApiModelProperty(example = "null", value = "")
  public InlineResponse2005DataBtcBalance getBtcBalance() {
    return btcBalance;
  }

  public void setBtcBalance(InlineResponse2005DataBtcBalance btcBalance) {
    this.btcBalance = btcBalance;
  }

  public InlineResponse2005Data fidorReservation(InlineResponse2005DataFidorReservation fidorReservation) {
    this.fidorReservation = fidorReservation;
    return this;
  }

   /**
   * Get fidorReservation
   * @return fidorReservation
  **/
  @ApiModelProperty(example = "null", value = "")
  public InlineResponse2005DataFidorReservation getFidorReservation() {
    return fidorReservation;
  }

  public void setFidorReservation(InlineResponse2005DataFidorReservation fidorReservation) {
    this.fidorReservation = fidorReservation;
  }

  public InlineResponse2005Data encryptedInformation(InlineResponse2005DataEncryptedInformation encryptedInformation) {
    this.encryptedInformation = encryptedInformation;
    return this;
  }

   /**
   * Get encryptedInformation
   * @return encryptedInformation
  **/
  @ApiModelProperty(example = "null", value = "")
  public InlineResponse2005DataEncryptedInformation getEncryptedInformation() {
    return encryptedInformation;
  }

  public void setEncryptedInformation(InlineResponse2005DataEncryptedInformation encryptedInformation) {
    this.encryptedInformation = encryptedInformation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005Data inlineResponse2005Data = (InlineResponse2005Data) o;
    return Objects.equals(this.btcBalance, inlineResponse2005Data.btcBalance) &&
        Objects.equals(this.fidorReservation, inlineResponse2005Data.fidorReservation) &&
        Objects.equals(this.encryptedInformation, inlineResponse2005Data.encryptedInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(btcBalance, fidorReservation, encryptedInformation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005Data {\n");
    
    sb.append("    btcBalance: ").append(toIndentedString(btcBalance)).append("\n");
    sb.append("    fidorReservation: ").append(toIndentedString(fidorReservation)).append("\n");
    sb.append("    encryptedInformation: ").append(toIndentedString(encryptedInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

