/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OrderRequirement
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T15:01:02.402+02:00")
public class OrderRequirement {
  @JsonProperty("min_trust_level")
  private TrustLevel minTrustLevel = null;

  @JsonProperty("only_kyc_full")
  private Boolean onlyKycFull = null;

  @JsonProperty("seat_of_bank")
  private List<BankList> seatOfBank = new ArrayList<BankList>();

  @JsonProperty("payment_option")
  private PaymentOption paymentOption = null;

  public OrderRequirement minTrustLevel(TrustLevel minTrustLevel) {
    this.minTrustLevel = minTrustLevel;
    return this;
  }

   /**
   * Get minTrustLevel
   * @return minTrustLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public TrustLevel getMinTrustLevel() {
    return minTrustLevel;
  }

  public void setMinTrustLevel(TrustLevel minTrustLevel) {
    this.minTrustLevel = minTrustLevel;
  }

  public OrderRequirement onlyKycFull(Boolean onlyKycFull) {
    this.onlyKycFull = onlyKycFull;
    return this;
  }

   /**
   * Handelspartner muss vollständig identifiziert sein
   * @return onlyKycFull
  **/
  @ApiModelProperty(example = "null", value = "Handelspartner muss vollständig identifiziert sein")
  public Boolean getOnlyKycFull() {
    return onlyKycFull;
  }

  public void setOnlyKycFull(Boolean onlyKycFull) {
    this.onlyKycFull = onlyKycFull;
  }

  public OrderRequirement seatOfBank(List<BankList> seatOfBank) {
    this.seatOfBank = seatOfBank;
    return this;
  }

  public OrderRequirement addSeatOfBankItem(BankList seatOfBankItem) {
    this.seatOfBank.add(seatOfBankItem);
    return this;
  }

   /**
   * Erlaubte Länder, in denen die Bank des Handelspartners ihren Sitz haben darf (ISO 3166-2)
   * @return seatOfBank
  **/
  @ApiModelProperty(example = "null", value = "Erlaubte Länder, in denen die Bank des Handelspartners ihren Sitz haben darf (ISO 3166-2)")
  public List<BankList> getSeatOfBank() {
    return seatOfBank;
  }

  public void setSeatOfBank(List<BankList> seatOfBank) {
    this.seatOfBank = seatOfBank;
  }

  public OrderRequirement paymentOption(PaymentOption paymentOption) {
    this.paymentOption = paymentOption;
    return this;
  }

   /**
   * Get paymentOption
   * @return paymentOption
  **/
  @ApiModelProperty(example = "null", value = "")
  public PaymentOption getPaymentOption() {
    return paymentOption;
  }

  public void setPaymentOption(PaymentOption paymentOption) {
    this.paymentOption = paymentOption;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderRequirement orderRequirement = (OrderRequirement) o;
    return Objects.equals(this.minTrustLevel, orderRequirement.minTrustLevel) &&
        Objects.equals(this.onlyKycFull, orderRequirement.onlyKycFull) &&
        Objects.equals(this.seatOfBank, orderRequirement.seatOfBank) &&
        Objects.equals(this.paymentOption, orderRequirement.paymentOption);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minTrustLevel, onlyKycFull, seatOfBank, paymentOption);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderRequirement {\n");
    
    sb.append("    minTrustLevel: ").append(toIndentedString(minTrustLevel)).append("\n");
    sb.append("    onlyKycFull: ").append(toIndentedString(onlyKycFull)).append("\n");
    sb.append("    seatOfBank: ").append(toIndentedString(seatOfBank)).append("\n");
    sb.append("    paymentOption: ").append(toIndentedString(paymentOption)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

