/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Positionstyp
 */
public enum PositionType {
  
  ALL("all"),
  
  BUY("buy"),
  
  SELL("sell"),
  
  INPAYMENT("inpayment"),
  
  PAYOUT("payout"),
  
  AFFILIATE("affiliate"),
  
  WELCOME_BTC("welcome_btc"),
  
  BUY_YUBIKEY("buy_yubikey"),
  
  BUY_GOLDSHOP("buy_goldshop"),
  
  BUY_DIAMONDSHOP("buy_diamondshop"),
  
  KICKBACK("kickback"),
  
  OUTGOING_FEE_VOLUNTARY("outgoing_fee_voluntary");

  private String value;

  PositionType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static PositionType fromValue(String text) {
    for (PositionType b : PositionType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

