/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * Verschlüsselte Infos
 */
@ApiModel(description = "Verschlüsselte Infos")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T15:01:02.402+02:00")
public class ShowAccountInfoResponseDataEncryptedInformation {
  @JsonProperty("bic_short")
  private String bicShort = null;

  @JsonProperty("bic_full")
  private String bicFull = null;

  @JsonProperty("uid")
  private String uid = null;

  public ShowAccountInfoResponseDataEncryptedInformation bicShort(String bicShort) {
    this.bicShort = bicShort;
    return this;
  }

   /**
   * Verschlüsselte Bankengruppe aus der BIC (ersten 4 Zeichen)
   * @return bicShort
  **/
  @ApiModelProperty(example = "null", value = "Verschlüsselte Bankengruppe aus der BIC (ersten 4 Zeichen)")
  public String getBicShort() {
    return bicShort;
  }

  public void setBicShort(String bicShort) {
    this.bicShort = bicShort;
  }

  public ShowAccountInfoResponseDataEncryptedInformation bicFull(String bicFull) {
    this.bicFull = bicFull;
    return this;
  }

   /**
   * Verschlüsselte komplette BIC
   * @return bicFull
  **/
  @ApiModelProperty(example = "null", value = "Verschlüsselte komplette BIC")
  public String getBicFull() {
    return bicFull;
  }

  public void setBicFull(String bicFull) {
    this.bicFull = bicFull;
  }

  public ShowAccountInfoResponseDataEncryptedInformation uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Verschlüsselte eigene User-Id
   * @return uid
  **/
  @ApiModelProperty(example = "null", value = "Verschlüsselte eigene User-Id")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowAccountInfoResponseDataEncryptedInformation showAccountInfoResponseDataEncryptedInformation = (ShowAccountInfoResponseDataEncryptedInformation) o;
    return Objects.equals(this.bicShort, showAccountInfoResponseDataEncryptedInformation.bicShort) &&
        Objects.equals(this.bicFull, showAccountInfoResponseDataEncryptedInformation.bicFull) &&
        Objects.equals(this.uid, showAccountInfoResponseDataEncryptedInformation.uid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bicShort, bicFull, uid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowAccountInfoResponseDataEncryptedInformation {\n");
    
    sb.append("    bicShort: ").append(toIndentedString(bicShort)).append("\n");
    sb.append("    bicFull: ").append(toIndentedString(bicFull)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

