/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ShowOrderbookResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T15:01:02.402+02:00")
public class ShowOrderbookResponse {
  @JsonProperty("orders")
  private List<ShowOrderbookResponseOrders> orders = new ArrayList<ShowOrderbookResponseOrders>();

  @JsonProperty("errors")
  private List<Error> errors = new ArrayList<Error>();

  @JsonProperty("credits")
  private Integer credits = null;

  public ShowOrderbookResponse orders(List<ShowOrderbookResponseOrders> orders) {
    this.orders = orders;
    return this;
  }

  public ShowOrderbookResponse addOrdersItem(ShowOrderbookResponseOrders ordersItem) {
    this.orders.add(ordersItem);
    return this;
  }

   /**
   * Get orders
   * @return orders
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ShowOrderbookResponseOrders> getOrders() {
    return orders;
  }

  public void setOrders(List<ShowOrderbookResponseOrders> orders) {
    this.orders = orders;
  }

  public ShowOrderbookResponse errors(List<Error> errors) {
    this.errors = errors;
    return this;
  }

  public ShowOrderbookResponse addErrorsItem(Error errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Error> getErrors() {
    return errors;
  }

  public void setErrors(List<Error> errors) {
    this.errors = errors;
  }

  public ShowOrderbookResponse credits(Integer credits) {
    this.credits = credits;
    return this;
  }

   /**
   * Restliches Credit-Kontingent
   * @return credits
  **/
  @ApiModelProperty(example = "null", value = "Restliches Credit-Kontingent")
  public Integer getCredits() {
    return credits;
  }

  public void setCredits(Integer credits) {
    this.credits = credits;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowOrderbookResponse showOrderbookResponse = (ShowOrderbookResponse) o;
    return Objects.equals(this.orders, showOrderbookResponse.orders) &&
        Objects.equals(this.errors, showOrderbookResponse.errors) &&
        Objects.equals(this.credits, showOrderbookResponse.credits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orders, errors, credits);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowOrderbookResponse {\n");
    
    sb.append("    orders: ").append(toIndentedString(orders)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    credits: ").append(toIndentedString(credits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

