/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.joda.time.DateTime;

/**
 * Infos zur ggfs. vorhandenen Fidor-Reservierung
 */
@ApiModel(description = "Infos zur ggfs. vorhandenen Fidor-Reservierung")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T15:01:02.402+02:00")
public class ShowAccountInfoResponseDataFidorReservation {
  @JsonProperty("total_amount")
  private Float totalAmount = null;

  @JsonProperty("available_amount")
  private Float availableAmount = null;

  @JsonProperty("reserved_at")
  private DateTime reservedAt = null;

  @JsonProperty("valid_until")
  private DateTime validUntil = null;

  public ShowAccountInfoResponseDataFidorReservation totalAmount(Float totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

   /**
   * Gesambetrag der Reservierung
   * @return totalAmount
  **/
  @ApiModelProperty(example = "null", value = "Gesambetrag der Reservierung")
  public Float getTotalAmount() {
    return totalAmount;
  }

  public void setTotalAmount(Float totalAmount) {
    this.totalAmount = totalAmount;
  }

  public ShowAccountInfoResponseDataFidorReservation availableAmount(Float availableAmount) {
    this.availableAmount = availableAmount;
    return this;
  }

   /**
   * Aktuell verfügbarer Betrag der Reservierung
   * @return availableAmount
  **/
  @ApiModelProperty(example = "null", value = "Aktuell verfügbarer Betrag der Reservierung")
  public Float getAvailableAmount() {
    return availableAmount;
  }

  public void setAvailableAmount(Float availableAmount) {
    this.availableAmount = availableAmount;
  }

  public ShowAccountInfoResponseDataFidorReservation reservedAt(DateTime reservedAt) {
    this.reservedAt = reservedAt;
    return this;
  }

   /**
   * Erstelldatum der Reservierung (Format: 2015-04-07T12:23:04+02:00 gemäß RFC 3339
   * @return reservedAt
  **/
  @ApiModelProperty(example = "null", value = "Erstelldatum der Reservierung (Format: 2015-04-07T12:23:04+02:00 gemäß RFC 3339")
  public DateTime getReservedAt() {
    return reservedAt;
  }

  public void setReservedAt(DateTime reservedAt) {
    this.reservedAt = reservedAt;
  }

  public ShowAccountInfoResponseDataFidorReservation validUntil(DateTime validUntil) {
    this.validUntil = validUntil;
    return this;
  }

   /**
   * Reservierung gültig bis (Format: 2015-04-07T12:23:04+02:00 gemäß RFC 3339)
   * @return validUntil
  **/
  @ApiModelProperty(example = "null", value = "Reservierung gültig bis (Format: 2015-04-07T12:23:04+02:00 gemäß RFC 3339)")
  public DateTime getValidUntil() {
    return validUntil;
  }

  public void setValidUntil(DateTime validUntil) {
    this.validUntil = validUntil;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowAccountInfoResponseDataFidorReservation showAccountInfoResponseDataFidorReservation = (ShowAccountInfoResponseDataFidorReservation) o;
    return Objects.equals(this.totalAmount, showAccountInfoResponseDataFidorReservation.totalAmount) &&
        Objects.equals(this.availableAmount, showAccountInfoResponseDataFidorReservation.availableAmount) &&
        Objects.equals(this.reservedAt, showAccountInfoResponseDataFidorReservation.reservedAt) &&
        Objects.equals(this.validUntil, showAccountInfoResponseDataFidorReservation.validUntil);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalAmount, availableAmount, reservedAt, validUntil);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowAccountInfoResponseDataFidorReservation {\n");
    
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    availableAmount: ").append(toIndentedString(availableAmount)).append("\n");
    sb.append("    reservedAt: ").append(toIndentedString(reservedAt)).append("\n");
    sb.append("    validUntil: ").append(toIndentedString(validUntil)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

