/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * Auflistung aller Balances
 */
@ApiModel(description = "Auflistung aller Balances")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-10T20:05:46.672+02:00")
public class ShowAccountInfoResponseDataBalances {
  @JsonProperty("btc")
  private ShowAccountInfoResponseDataBtcBalancesBtc btc = null;

  @JsonProperty("bch")
  private ShowAccountInfoResponseDataBtcBalancesBch bch = null;

  @JsonProperty("eth")
  private ShowAccountInfoResponseDataBtcBalancesEth eth = null;

  public ShowAccountInfoResponseDataBalances btc(ShowAccountInfoResponseDataBtcBalancesBtc btc) {
    this.btc = btc;
    return this;
  }

   /**
   * Get btc
   * @return btc
  **/
  @ApiModelProperty(example = "null", value = "")
  public ShowAccountInfoResponseDataBtcBalancesBtc getBtc() {
    return btc;
  }

  public void setBtc(ShowAccountInfoResponseDataBtcBalancesBtc btc) {
    this.btc = btc;
  }

  public ShowAccountInfoResponseDataBalances bch(ShowAccountInfoResponseDataBtcBalancesBch bch) {
    this.bch = bch;
    return this;
  }

   /**
   * Get bch
   * @return bch
  **/
  @ApiModelProperty(example = "null", value = "")
  public ShowAccountInfoResponseDataBtcBalancesBch getBch() {
    return bch;
  }

  public void setBch(ShowAccountInfoResponseDataBtcBalancesBch bch) {
    this.bch = bch;
  }

  public ShowAccountInfoResponseDataBalances eth(ShowAccountInfoResponseDataBtcBalancesEth eth) {
    this.eth = eth;
    return this;
  }

   /**
   * Get eth
   * @return eth
  **/
  @ApiModelProperty(example = "null", value = "")
  public ShowAccountInfoResponseDataBtcBalancesEth getEth() {
    return eth;
  }

  public void setEth(ShowAccountInfoResponseDataBtcBalancesEth eth) {
    this.eth = eth;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowAccountInfoResponseDataBalances showAccountInfoResponseDataBalances = (ShowAccountInfoResponseDataBalances) o;
    return Objects.equals(this.btc, showAccountInfoResponseDataBalances.btc) &&
        Objects.equals(this.bch, showAccountInfoResponseDataBalances.bch) &&
        Objects.equals(this.eth, showAccountInfoResponseDataBalances.eth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(btc, bch, eth);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowAccountInfoResponseDataBalances {\n");
    
    sb.append("    btc: ").append(toIndentedString(btc)).append("\n");
    sb.append("    bch: ").append(toIndentedString(bch)).append("\n");
    sb.append("    eth: ").append(toIndentedString(eth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

