/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ShowPublicTradeHistoryResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-10T20:05:46.672+02:00")
public class ShowPublicTradeHistoryResponse {
  @JsonProperty("trading_pair")
  private TradingPair tradingPair = null;

  @JsonProperty("trades")
  private List<ShowPublicTradeHistoryResponseTrades> trades = new ArrayList<ShowPublicTradeHistoryResponseTrades>();

  @JsonProperty("errors")
  private List<Error> errors = new ArrayList<Error>();

  @JsonProperty("credits")
  private Integer credits = null;

  public ShowPublicTradeHistoryResponse tradingPair(TradingPair tradingPair) {
    this.tradingPair = tradingPair;
    return this;
  }

   /**
   * Get tradingPair
   * @return tradingPair
  **/
  @ApiModelProperty(example = "null", value = "")
  public TradingPair getTradingPair() {
    return tradingPair;
  }

  public void setTradingPair(TradingPair tradingPair) {
    this.tradingPair = tradingPair;
  }

  public ShowPublicTradeHistoryResponse trades(List<ShowPublicTradeHistoryResponseTrades> trades) {
    this.trades = trades;
    return this;
  }

  public ShowPublicTradeHistoryResponse addTradesItem(ShowPublicTradeHistoryResponseTrades tradesItem) {
    this.trades.add(tradesItem);
    return this;
  }

   /**
   * 
   * @return trades
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ShowPublicTradeHistoryResponseTrades> getTrades() {
    return trades;
  }

  public void setTrades(List<ShowPublicTradeHistoryResponseTrades> trades) {
    this.trades = trades;
  }

  public ShowPublicTradeHistoryResponse errors(List<Error> errors) {
    this.errors = errors;
    return this;
  }

  public ShowPublicTradeHistoryResponse addErrorsItem(Error errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Error> getErrors() {
    return errors;
  }

  public void setErrors(List<Error> errors) {
    this.errors = errors;
  }

  public ShowPublicTradeHistoryResponse credits(Integer credits) {
    this.credits = credits;
    return this;
  }

   /**
   * Restliches Credit-Kontingent
   * @return credits
  **/
  @ApiModelProperty(example = "null", value = "Restliches Credit-Kontingent")
  public Integer getCredits() {
    return credits;
  }

  public void setCredits(Integer credits) {
    this.credits = credits;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowPublicTradeHistoryResponse showPublicTradeHistoryResponse = (ShowPublicTradeHistoryResponse) o;
    return Objects.equals(this.tradingPair, showPublicTradeHistoryResponse.tradingPair) &&
        Objects.equals(this.trades, showPublicTradeHistoryResponse.trades) &&
        Objects.equals(this.errors, showPublicTradeHistoryResponse.errors) &&
        Objects.equals(this.credits, showPublicTradeHistoryResponse.credits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradingPair, trades, errors, credits);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowPublicTradeHistoryResponse {\n");
    
    sb.append("    tradingPair: ").append(toIndentedString(tradingPair)).append("\n");
    sb.append("    trades: ").append(toIndentedString(trades)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    credits: ").append(toIndentedString(credits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

