/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * Tradedetails (nur bei Typ sell/buy)
 */
@ApiModel(description = "Tradedetails (nur bei Typ sell/buy)")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T15:01:02.402+02:00")
public class ShowAccountLedgerResponseTrade {
  @JsonProperty("trade_id")
  private String tradeId = null;

  @JsonProperty("price")
  private String price = null;

  @JsonProperty("btc")
  private ShowAccountLedgerResponseTradeBtc btc = null;

  @JsonProperty("euro")
  private ShowAccountLedgerResponseTradeEuro euro = null;

  public ShowAccountLedgerResponseTrade tradeId(String tradeId) {
    this.tradeId = tradeId;
    return this;
  }

   /**
   * ID des Trades
   * @return tradeId
  **/
  @ApiModelProperty(example = "null", value = "ID des Trades")
  public String getTradeId() {
    return tradeId;
  }

  public void setTradeId(String tradeId) {
    this.tradeId = tradeId;
  }

  public ShowAccountLedgerResponseTrade price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Preis pro Bitcoin in Euro
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "Preis pro Bitcoin in Euro")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public ShowAccountLedgerResponseTrade btc(ShowAccountLedgerResponseTradeBtc btc) {
    this.btc = btc;
    return this;
  }

   /**
   * Get btc
   * @return btc
  **/
  @ApiModelProperty(example = "null", value = "")
  public ShowAccountLedgerResponseTradeBtc getBtc() {
    return btc;
  }

  public void setBtc(ShowAccountLedgerResponseTradeBtc btc) {
    this.btc = btc;
  }

  public ShowAccountLedgerResponseTrade euro(ShowAccountLedgerResponseTradeEuro euro) {
    this.euro = euro;
    return this;
  }

   /**
   * Get euro
   * @return euro
  **/
  @ApiModelProperty(example = "null", value = "")
  public ShowAccountLedgerResponseTradeEuro getEuro() {
    return euro;
  }

  public void setEuro(ShowAccountLedgerResponseTradeEuro euro) {
    this.euro = euro;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowAccountLedgerResponseTrade showAccountLedgerResponseTrade = (ShowAccountLedgerResponseTrade) o;
    return Objects.equals(this.tradeId, showAccountLedgerResponseTrade.tradeId) &&
        Objects.equals(this.price, showAccountLedgerResponseTrade.price) &&
        Objects.equals(this.btc, showAccountLedgerResponseTrade.btc) &&
        Objects.equals(this.euro, showAccountLedgerResponseTrade.euro);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradeId, price, btc, euro);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowAccountLedgerResponseTrade {\n");
    
    sb.append("    tradeId: ").append(toIndentedString(tradeId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    btc: ").append(toIndentedString(btc)).append("\n");
    sb.append("    euro: ").append(toIndentedString(euro)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

