/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.joda.time.DateTime;

/**
 * ShowAccountLedgerResponseAccountLedger
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T15:01:02.402+02:00")
public class ShowAccountLedgerResponseAccountLedger {
  @JsonProperty("date")
  private DateTime date = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("reference")
  private String reference = null;

  @JsonProperty("trade")
  private ShowAccountLedgerResponseTrade trade = null;

  @JsonProperty("cashflow")
  private String cashflow = null;

  @JsonProperty("balance")
  private String balance = null;

  public ShowAccountLedgerResponseAccountLedger date(DateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Buchungsdatum (Format: 2015-04-07T12:23:04+02:00 gemäß RFC 3339)
   * @return date
  **/
  @ApiModelProperty(example = "null", value = "Buchungsdatum (Format: 2015-04-07T12:23:04+02:00 gemäß RFC 3339)")
  public DateTime getDate() {
    return date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public ShowAccountLedgerResponseAccountLedger type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Typ der Position
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "Typ der Position")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ShowAccountLedgerResponseAccountLedger reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Referenz zu der Position (trade_id bei buy/sell oder txid bei einer Einzahlung/Auszahlung)
   * @return reference
  **/
  @ApiModelProperty(example = "null", value = "Referenz zu der Position (trade_id bei buy/sell oder txid bei einer Einzahlung/Auszahlung)")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public ShowAccountLedgerResponseAccountLedger trade(ShowAccountLedgerResponseTrade trade) {
    this.trade = trade;
    return this;
  }

   /**
   * Get trade
   * @return trade
  **/
  @ApiModelProperty(example = "null", value = "")
  public ShowAccountLedgerResponseTrade getTrade() {
    return trade;
  }

  public void setTrade(ShowAccountLedgerResponseTrade trade) {
    this.trade = trade;
  }

  public ShowAccountLedgerResponseAccountLedger cashflow(String cashflow) {
    this.cashflow = cashflow;
    return this;
  }

   /**
   * Zu- / Abgang
   * @return cashflow
  **/
  @ApiModelProperty(example = "null", value = "Zu- / Abgang")
  public String getCashflow() {
    return cashflow;
  }

  public void setCashflow(String cashflow) {
    this.cashflow = cashflow;
  }

  public ShowAccountLedgerResponseAccountLedger balance(String balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Kontostand
   * @return balance
  **/
  @ApiModelProperty(example = "null", value = "Kontostand")
  public String getBalance() {
    return balance;
  }

  public void setBalance(String balance) {
    this.balance = balance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowAccountLedgerResponseAccountLedger showAccountLedgerResponseAccountLedger = (ShowAccountLedgerResponseAccountLedger) o;
    return Objects.equals(this.date, showAccountLedgerResponseAccountLedger.date) &&
        Objects.equals(this.type, showAccountLedgerResponseAccountLedger.type) &&
        Objects.equals(this.reference, showAccountLedgerResponseAccountLedger.reference) &&
        Objects.equals(this.trade, showAccountLedgerResponseAccountLedger.trade) &&
        Objects.equals(this.cashflow, showAccountLedgerResponseAccountLedger.cashflow) &&
        Objects.equals(this.balance, showAccountLedgerResponseAccountLedger.balance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, type, reference, trade, cashflow, balance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowAccountLedgerResponseAccountLedger {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    trade: ").append(toIndentedString(trade)).append("\n");
    sb.append("    cashflow: ").append(toIndentedString(cashflow)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

