/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Array mit Bids / Asks
 */
@ApiModel(description = "Array mit Bids / Asks")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T15:01:02.402+02:00")
public class ShowOrderbookCompactResponseOrders {
  @JsonProperty("bids")
  private List<ShowOrderbookCompactResponseOrdersBids> bids = new ArrayList<ShowOrderbookCompactResponseOrdersBids>();

  @JsonProperty("asks")
  private List<ShowOrderbookCompactResponseOrdersBids> asks = new ArrayList<ShowOrderbookCompactResponseOrdersBids>();

  public ShowOrderbookCompactResponseOrders bids(List<ShowOrderbookCompactResponseOrdersBids> bids) {
    this.bids = bids;
    return this;
  }

  public ShowOrderbookCompactResponseOrders addBidsItem(ShowOrderbookCompactResponseOrdersBids bidsItem) {
    this.bids.add(bidsItem);
    return this;
  }

   /**
   * Get bids
   * @return bids
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ShowOrderbookCompactResponseOrdersBids> getBids() {
    return bids;
  }

  public void setBids(List<ShowOrderbookCompactResponseOrdersBids> bids) {
    this.bids = bids;
  }

  public ShowOrderbookCompactResponseOrders asks(List<ShowOrderbookCompactResponseOrdersBids> asks) {
    this.asks = asks;
    return this;
  }

  public ShowOrderbookCompactResponseOrders addAsksItem(ShowOrderbookCompactResponseOrdersBids asksItem) {
    this.asks.add(asksItem);
    return this;
  }

   /**
   * Get asks
   * @return asks
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ShowOrderbookCompactResponseOrdersBids> getAsks() {
    return asks;
  }

  public void setAsks(List<ShowOrderbookCompactResponseOrdersBids> asks) {
    this.asks = asks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowOrderbookCompactResponseOrders showOrderbookCompactResponseOrders = (ShowOrderbookCompactResponseOrders) o;
    return Objects.equals(this.bids, showOrderbookCompactResponseOrders.bids) &&
        Objects.equals(this.asks, showOrderbookCompactResponseOrders.asks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bids, asks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowOrderbookCompactResponseOrders {\n");
    
    sb.append("    bids: ").append(toIndentedString(bids)).append("\n");
    sb.append("    asks: ").append(toIndentedString(asks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

