/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * Tradedetails (nur bei Typ sell/buy)
 */
@ApiModel(description = "Tradedetails (nur bei Typ sell/buy)")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-10T20:05:46.672+02:00")
public class ShowAccountLedgerResponseTrade {
  @JsonProperty("trade_id")
  private String tradeId = null;

  @JsonProperty("trading_pair")
  private TradingPair tradingPair = null;

  @JsonProperty("price")
  private String price = null;

  @JsonProperty("primary_currency")
  private CryptoCurrencySum primaryCurrency = null;

  @JsonProperty("secondary_currency")
  private CryptoCurrencySum secondaryCurrency = null;

  public ShowAccountLedgerResponseTrade tradeId(String tradeId) {
    this.tradeId = tradeId;
    return this;
  }

   /**
   * ID des Trades
   * @return tradeId
  **/
  @ApiModelProperty(example = "null", value = "ID des Trades")
  public String getTradeId() {
    return tradeId;
  }

  public void setTradeId(String tradeId) {
    this.tradeId = tradeId;
  }

  public ShowAccountLedgerResponseTrade tradingPair(TradingPair tradingPair) {
    this.tradingPair = tradingPair;
    return this;
  }

   /**
   * Handelspaar
   * @return tradingPair
  **/
  @ApiModelProperty(example = "null", value = "Handelspaar")
  public TradingPair getTradingPair() {
    return tradingPair;
  }

  public void setTradingPair(TradingPair tradingPair) {
    this.tradingPair = tradingPair;
  }

  public ShowAccountLedgerResponseTrade price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Preis pro Bitcoin in Euro
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "Preis pro Bitcoin in Euro")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public ShowAccountLedgerResponseTrade primaryCurrency(CryptoCurrencySum primaryCurrency) {
    this.primaryCurrency = primaryCurrency;
    return this;
  }

   /**
   * Get primaryCurrency
   * @return primaryCurrency
  **/
  @ApiModelProperty(example = "null", value = "")
  public CryptoCurrencySum getPrimaryCurrency() {
    return primaryCurrency;
  }

  public void setPrimaryCurrency(CryptoCurrencySum primaryCurrency) {
    this.primaryCurrency = primaryCurrency;
  }

  public ShowAccountLedgerResponseTrade secondaryCurrency(CryptoCurrencySum secondaryCurrency) {
    this.secondaryCurrency = secondaryCurrency;
    return this;
  }

   /**
   * Get secondaryCurrency
   * @return secondaryCurrency
  **/
  @ApiModelProperty(example = "null", value = "")
  public CryptoCurrencySum getSecondaryCurrency() {
    return secondaryCurrency;
  }

  public void setSecondaryCurrency(CryptoCurrencySum secondaryCurrency) {
    this.secondaryCurrency = secondaryCurrency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShowAccountLedgerResponseTrade showAccountLedgerResponseTrade = (ShowAccountLedgerResponseTrade) o;
    return Objects.equals(this.tradeId, showAccountLedgerResponseTrade.tradeId) &&
        Objects.equals(this.tradingPair, showAccountLedgerResponseTrade.tradingPair) &&
        Objects.equals(this.price, showAccountLedgerResponseTrade.price) &&
        Objects.equals(this.primaryCurrency, showAccountLedgerResponseTrade.primaryCurrency) &&
        Objects.equals(this.secondaryCurrency, showAccountLedgerResponseTrade.secondaryCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradeId, tradingPair, price, primaryCurrency, secondaryCurrency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShowAccountLedgerResponseTrade {\n");
    
    sb.append("    tradeId: ").append(toIndentedString(tradeId)).append("\n");
    sb.append("    tradingPair: ").append(toIndentedString(tradingPair)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    primaryCurrency: ").append(toIndentedString(primaryCurrency)).append("\n");
    sb.append("    secondaryCurrency: ").append(toIndentedString(secondaryCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

