/*
 * bitcoin.de API
 * This specification describe the public api of bitcoin.de
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.rainu.bitcoinde.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.rainu.bitcoinde.model.TrustLevel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TradingPartner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-27T13:21:29.350+02:00")
public class TradingPartner {
  @JsonProperty("username")
  private String username = null;

  @JsonProperty("is_kyc_full")
  private Boolean isKycFull = null;

  @JsonProperty("trust_level")
  private TrustLevel trustLevel = null;

  @JsonProperty("bank_name")
  private String bankName = null;

  @JsonProperty("bic")
  private String bic = null;

  @JsonProperty("rating")
  private Integer rating = null;

  @JsonProperty("amount_trades")
  private Integer amountTrades = null;

  public TradingPartner username(String username) {
    this.username = username;
    return this;
  }

   /**
   * User-Name
   * @return username
  **/
  @ApiModelProperty(example = "null", value = "User-Name")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public TradingPartner isKycFull(Boolean isKycFull) {
    this.isKycFull = isKycFull;
    return this;
  }

   /**
   * Vollständig identifizierter User
   * @return isKycFull
  **/
  @ApiModelProperty(example = "null", value = "Vollständig identifizierter User")
  public Boolean getIsKycFull() {
    return isKycFull;
  }

  public void setIsKycFull(Boolean isKycFull) {
    this.isKycFull = isKycFull;
  }

  public TradingPartner trustLevel(TrustLevel trustLevel) {
    this.trustLevel = trustLevel;
    return this;
  }

   /**
   * Get trustLevel
   * @return trustLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public TrustLevel getTrustLevel() {
    return trustLevel;
  }

  public void setTrustLevel(TrustLevel trustLevel) {
    this.trustLevel = trustLevel;
  }

  public TradingPartner bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * Name der Bank
   * @return bankName
  **/
  @ApiModelProperty(example = "null", value = "Name der Bank")
  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public TradingPartner bic(String bic) {
    this.bic = bic;
    return this;
  }

   /**
   * BIC der Bank
   * @return bic
  **/
  @ApiModelProperty(example = "null", value = "BIC der Bank")
  public String getBic() {
    return bic;
  }

  public void setBic(String bic) {
    this.bic = bic;
  }

  public TradingPartner rating(Integer rating) {
    this.rating = rating;
    return this;
  }

   /**
   * Prozentualer Anteil an positiven Bewertungen durch die Handelspartner
   * @return rating
  **/
  @ApiModelProperty(example = "null", value = "Prozentualer Anteil an positiven Bewertungen durch die Handelspartner")
  public Integer getRating() {
    return rating;
  }

  public void setRating(Integer rating) {
    this.rating = rating;
  }

  public TradingPartner amountTrades(Integer amountTrades) {
    this.amountTrades = amountTrades;
    return this;
  }

   /**
   * Anzahl bereits getätigten Trades
   * @return amountTrades
  **/
  @ApiModelProperty(example = "null", value = "Anzahl bereits getätigten Trades")
  public Integer getAmountTrades() {
    return amountTrades;
  }

  public void setAmountTrades(Integer amountTrades) {
    this.amountTrades = amountTrades;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TradingPartner tradingPartner = (TradingPartner) o;
    return Objects.equals(this.username, tradingPartner.username) &&
        Objects.equals(this.isKycFull, tradingPartner.isKycFull) &&
        Objects.equals(this.trustLevel, tradingPartner.trustLevel) &&
        Objects.equals(this.bankName, tradingPartner.bankName) &&
        Objects.equals(this.bic, tradingPartner.bic) &&
        Objects.equals(this.rating, tradingPartner.rating) &&
        Objects.equals(this.amountTrades, tradingPartner.amountTrades);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, isKycFull, trustLevel, bankName, bic, rating, amountTrades);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TradingPartner {\n");
    
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    isKycFull: ").append(toIndentedString(isKycFull)).append("\n");
    sb.append("    trustLevel: ").append(toIndentedString(trustLevel)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    amountTrades: ").append(toIndentedString(amountTrades)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

